Name: API-BASE
Version: 0.0.0
PprofPort: :5555
Mode: debug                 # debug, release, test
JwtSecret: JWT_SECRET
JwtTimeout: 86400
CookieName: jwt-token
SSL: true
CtxDefaultTimeout: 12
CSRF: true
Debug: false
EnableTrace: false
EnablePprof: true

HTTP:
  Addr: 0.0.0.0:8192
  ReadTimeout: 3s
  WriteTimeout: 3s
